server:
  port: 8013

my:
  value: "config client refreshed2"
  
spring:
  rabbitmq:
    host: 192.168.0.2
    port: 5672
    username: nvtadmin
    password: nvtpass

management:
  endpoints:
    web: 
      exposure:
        include: "refresh"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
    